batch_size: 512
batches_per_epoch: 2000
chunk_size: 10000
chunks_per_epoch: 10
data_dir: /home/seiya.tsukamoto/aframe/layered/data/train
fduration: 1.0
fftlength: null
file_sample_rate: 2048.0
highpass: 32.0
ifos:
- H1
- L1
kernel_length: 4.0
learning_rate: 0.000585
left_pad: 0.25
lowpass: 64.0
max_snr: 100.0
min_valid_duration: 15000.0
mute_prob: 0.055
num_files_per_batch: 10
num_valid_views: 5
pct_lr_ramp: 0.115
psd_length: 8.0
resample_rate: 512.0
resampler: !!python/object:torchaudio.transforms._transforms.Resample
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers:
    kernel: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYDgAAADk0Mjg1OTIzNjk2ODQ4cQJYAwAAAGNwdXEDSzZOdHEEUS6AAl1xAFgOAAAAOTQy
        ODU5MjM2OTY4NDhxAWEuNgAAAAAAAAAAAACAlpcktcZmmrjmp5y5PvbIuataQDlHFsQ6tbIxOxpC
        GDtTXym6I4atu1KADLw8f+C70CqmOvi7TzxRQqU8c0+EPCYU97oDNeC8CN85vfQQH72ZDRk7XV2X
        PbU7ID57tGM+pHB9Pnu0Yz61OyA+XV2XPZkNGTv0EB+9CN85vQM14LwmFPe6c0+EPFFCpTz4u088
        0CqmOjx/4LtSgAy8I4atu1NfKboaQhg7tbIxO0cWxDqrWkA5PvbIueannLnGZpq4lpcktQAAAIAA
        AACAAAAAgAAAAIA=
    - 0
    - !!python/tuple
      - 1
      - 1
      - 54
    - !!python/tuple
      - 54
      - 54
      - 1
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: {}
  _non_persistent_buffers_set: !!set {}
  _parameters: {}
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  beta: null
  gcd: 512
  lowpass_filter_width: 6
  new_freq: 512
  orig_freq: 2048
  resampling_method: sinc_interp_hann
  rolloff: 0.99
  training: true
  width: 25
right_pad: 0.05
sample_rate: 2048.0
snr_alpha: 3.0
snr_sampler: !!python/object:ml4gw.distributions.PowerLaw
  _batch_shape: !!python/object/apply:torch.Size
  - !!python/tuple []
  _event_shape: !!python/object/apply:torch.Size
  - !!python/tuple []
  base_dist: !!python/object:torch.distributions.uniform.Uniform
    _batch_shape: !!python/object/apply:torch.Size
    - !!python/tuple []
    _event_shape: !!python/object/apply:torch.Size
    - !!python/tuple []
    _validate_args: false
    high: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYDgAAADk0Mjg1OTIyMzE4NzA0cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgOAAAAOTQy
        ODU5MjIzMTg3MDRxAWEuAQAAAAAAAAAXt1G4
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    low: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYDgAAADk0Mjg1OTE4ODM2MzM2cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgOAAAAOTQy
        ODU5MTg4MzYzMzZxAWEuAQAAAAAAAAAAAAC9
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
  transforms:
  - !!python/object:torch.distributions.transforms.AffineTransform
    _cache_size: 0
    _event_dim: 0
    _inv: null
    loc: 0
    scale: -2
  - !!python/object:torch.distributions.transforms.PowerTransform
    _cache_size: 0
    _inv: null
    exponent: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYDgAAADk0Mjg1OTE4NjU1MDg4cQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgOAAAAOTQy
        ODU5MTg2NTUwODhxAWEuAQAAAAAAAAAAAAC/
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
swap_prob: 0.014
valid_frac: 0.25
valid_livetime: 57600.0
valid_stride: 0.5
verbose: false
waveform_prob: 0.277
weight_decay: 0.0
