_wandb:
    value:
        cli_version: 0.18.7
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 55
                - 106
            "2":
                - 1
                - 55
                - 106
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.10.16
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 512
batches_per_epoch:
    value: 2000
chunk_size:
    value: 10000
chunks_per_epoch:
    value: 10
ckpt_path:
    value: null
config:
    value:
        - /home/seiya.tsukamoto/aframe/layered/512_32_64_4/train.yaml
data:
    value:
        class_path: train.data.supervised.ResampledAframeDataset_v2
        init_args:
            batch_size: 512
            batches_per_epoch: 2000
            chunk_size: 10000
            chunks_per_epoch: 10
            data_dir: /home/seiya.tsukamoto/aframe/layered/data/train
            fduration: 1
            fftlength: null
            file_sample_rate: 2048
            highpass: 32
            ifos:
                - H1
                - L1
            kernel_length: 4
            left_pad: 0.25
            lowpass: 64
            max_snr: 100
            min_valid_duration: 15000
            mute_prob: 0.055
            num_files_per_batch: 10
            num_valid_views: 5
            psd_length: 8
            resampler:
                class_path: torchaudio.transforms.Resample
                init_args:
                    beta: null
                    dtype: null
                    lowpass_filter_width: 6
                    new_freq: 512
                    orig_freq: 2048
                    resampling_method: sinc_interp_hann
                    rolloff: 0.99
            right_pad: 0.05
            sample_rate: 512
            snr_alpha: 3
            snr_sampler:
                class_path: ml4gw.distributions.PowerLaw
                init_args:
                    index: -3
                    maximum: 100
                    minimum: 4
                    validate_args: null
            swap_prob: 0.014
            valid_frac: 0.25
            valid_livetime: 57600
            valid_stride: 0.5
            verbose: false
            waveform_prob: 0.277
data_dir:
    value: /home/seiya.tsukamoto/aframe/layered/data/train
fduration:
    value: 1
fftlength:
    value: null
file_sample_rate:
    value: 2048
highpass:
    value: 32
ifos:
    value:
        - H1
        - L1
kernel_length:
    value: 4
learning_rate:
    value: 0.000585
left_pad:
    value: 0.25
lowpass:
    value: 64
lr_scheduler:
    value: null
max_snr:
    value: 100
min_valid_duration:
    value: 15000
model:
    value:
        class_path: train.model.SupervisedAframe
        init_args:
            arch:
                class_path: architectures.Bandpass
                init_args:
                    classes: 64
                    groups: 1
                    kernel_length: 4
                    kernel_size: 3
                    layers:
                        - 3
                        - 4
                        - 6
                        - 3
                    norm_layer:
                        class_path: ml4gw.nn.norm.GroupNorm1DGetter
                        init_args:
                            groups: 16
                    num_ifos: null
                    sample_rate: 512
                    stride_type: null
                    truncate: false
                    width_per_group: 64
                    zero_init_residual: false
            learning_rate: 0.000585
            metric:
                class_path: train.metrics.TimeSlideAUROC
                init_args:
                    compute_on_cpu: false
                    dist_sync_fn: null
                    dist_sync_on_step: false
                    max_fpr: 0.001
                    pool_length: 8
                    process_group: null
                    stride: 0.5
                    sync_on_compute: true
            pct_lr_ramp: 0.115
            verbose: false
            weight_decay: 0
mute_prob:
    value: 0.055
num_files_per_batch:
    value: 10
num_valid_views:
    value: 5
optimizer:
    value: null
pct_lr_ramp:
    value: 0.115
psd_length:
    value: 8
resampler:
    value: null
right_pad:
    value: 0.05
sample_rate:
    value: 512
seed_everything:
    value: 1122
snr_alpha:
    value: 3
snr_sampler:
    value: PowerLaw()
swap_prob:
    value: 0.014
valid_frac:
    value: 0.25
valid_livetime:
    value: 57600
valid_stride:
    value: 0.5
verbose:
    value: false
waveform_prob:
    value: 0.277
weight_decay:
    value: 0
